apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: mean-demo-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: backend
  name: nginx
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
