apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mean-demo4
    app.kubernetes.io/instance: mean-demo-instance
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: backend
  name: mean-demo4
spec:
  selector:
    app: mean-demo4
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4040  

